### ISSUE TITLE
I got error while testing audio record in Android 7.1

### ISSUE THREAD

**Issue by sciage** [JimSeker/AudioVideo#1]
Error was failed to transfer result from permissions

FATAL EXCEPTION: main
                                                                        Process: edu.cs4730.AudioRecord, PID: 20338
                                                                        java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {edu.cs4730.AudioRecord/edu.cs4730.AudioRecord.MainActivity}: java.lang.RuntimeException: start failed.
                                                                            at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
                                                                            at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
                                                                            at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                         Caused by: java.lang.RuntimeException: start failed.
                                                                            at android.media.MediaRecorder.start(Native Method)
                                                                            at edu.cs4730.AudioRecord.MainFragment.startRecording(MainFragment.java:138)
                                                                            at edu.cs4730.AudioRecord.MainActivity.onRequestPermissionsResult(MainActivity.java:54)
                                                                            at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7084)
                                                                            at android.app.Activity.dispatchActivityResult(Activity.java:6936)
                                                                            at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
                                                                            at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
                                                                            at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by sciage** [comment]
Error inside MainActivity

/MainActivity: Both permissions has now been granted. Starting Demo.
02-18 06:43:56.571 20338-20338/edu.cs4730.AudioRecord E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: edu.cs4730.AudioRecord, PID: 20338
                                                                        java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {edu.cs4730.AudioRecord/edu.cs4730.AudioRecord.MainActivity}: java.lang.RuntimeException: start failed.
                                                                            at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
                                                                            at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
                                                                            at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                         Caused by: java.lang.RuntimeException: start failed.
                                                                            at android.media.MediaRecorder.start(Native Method)
                                                                            at edu.cs4730.AudioRecord.MainFragment.startRecording(MainFragment.java:138)
                                                                            at edu.cs4730.AudioRecord.MainActivity.onRequestPermissionsResult(MainActivity.java:54)
                                                                            at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7084)
                                                                            at android.app.Activity.dispatchActivityResult(Activity.java:6936)
                                                                            at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
                                                                            at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
                                                                            at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
